### ISSUE TITLE
no php

### ISSUE THREAD

**Issue by MooShoe** [Scratchcoin/Scratchcoin#4]
no plz we use node.js

**Comment by TropicSapling** [comment]
n plz use Go node.js was a mistake

**Comment by MooShoe** [comment]
i dont know go

**Comment by TropicSapling** [comment]
https://golang.org

**Comment by MooShoe** [comment]
go is too simple. we're looking for something with more power.\

good job moving to node.js bubz, but using sockets.io for login? time to move issues
